
import { FileNode } from './types';

export const INITIAL_FILE_STRUCTURE: FileNode[] = [
  {
    id: 'core-root',
    name: 'Core',
    type: 'folder',
    path: '/Core',
    children: [
      { id: 'core-character-class', name: 'CharacterClass.cpp', type: 'file', path: '/Core/CharacterClass.cpp' },
      { id: 'core-chimera-render', name: 'ChimeraRender.hpp', type: 'file', path: '/Core/ChimeraRender.hpp' }
    ]
  },
  {
    id: 'source-root',
    name: 'Source',
    type: 'folder',
    path: '/Source',
    children: [
      { id: 'source-client', name: 'Client', type: 'folder', path: '/Source/Client' },
      { id: 'source-server', name: 'Server', type: 'folder', path: '/Source/Server' },
      { id: 'source-configs', name: 'Configs', type: 'folder', path: '/Source/Configs' }
    ]
  },
  {
    id: 'assets-root',
    name: 'Assets',
    type: 'folder',
    path: '/Assets',
    children: [
      { id: 'assets-characters', name: 'Characters', type: 'folder', path: '/Assets/Characters' },
      { id: 'assets-animations', name: 'Animations', type: 'folder', path: '/Assets/Animations' },
      { id: 'assets-textures', name: 'Textures', type: 'folder', path: '/Assets/Textures' }
    ]
  },
  { id: 'game-design-doc', name: 'GameDesignDoc.md', type: 'file', path: '/GameDesignDoc.md' },
  { id: 'cluster-config-yaml', name: 'cluster_config.yaml', type: 'file', path: '/cluster_config.yaml' }
];

export const TRANSLATIONS = {
  EN: {
    architect: "Architect AI",
    build: "Build",
    deploy: "Deploy",
    project: "Project",
    settings: "Settings",
    aiPrompt: "Ask the Architect...",
    statusReady: "Ready",
    statusCompiling: "Compiling...",
    profile: "Profile",
    terminal: "Terminal",
    explorer: "Explorer",
    tabScene: "Scene",
    tabCode: "Code",
    tabNetGraph: "NetGraph",
    tabAssets: "Asset Studio",
    tabOrchestrator: "Orchestrator",
    generate: "Generate",
    deployCluster: "Deploy Cluster",
    stopCluster: "Stop Cluster",
    apply: "Apply Changes",
    scanArchitecture: "Scan Architecture",
    compileBuild: "Compile Build",
    projectHierarchy: "Project Hierarchy",
    kernelOutput: "Kernel Output",
    complexity: "Complexity",
    threads: "Threads",
    diagnostics: "Diagnostics",
    autoPatch: "Auto-Patch",
    meshGen: "Mesh Generation",
    motionBank: "MotionBank",
    loadConcept: "Load Concept",
    directives: "Directives",
    startSynthesis: "Start Neural Synthesis",
    synthesizing: "Synthesizing...",
    finalizeImport: "Finalize Import",
    neuralMotion: "Neural Motion Synthesis",
    describeMotion: "Describe motion (e.g. 'Jump')...",
    synthesizeAnimation: "Synthesize Animation",
    topology: "Topology Insights",
    addNode: "Add node...",
    synthesizeNode: "Synthesize",
    pipeline: "Pipeline",
    lodIndex: "LOD Index",
    nodeLoad: "Node Load",
    infrastructure: "Infrastructure Monitor",
    realtimeStream: "Real-time Stream: Active",
    specYaml: "Specification YAML",
    provisioning: "Provisioning...",
    autosave: "Autosave",
    enabled: "Enabled",
    thinking: "Architect Thinking...",
    proactiveContext: "Proactive Context",
    recArch: "Architecture recommendation",
    sysNominal: "Systems nominal. Performing background performance audit...",
    assetPreview: "Asset Preview",
    weightsConverged: "Weights Converged",
    neuralStandby: "Neural Pipeline Standby",
    addRetargeter: "Add to Retargeter",
    synthesizeModule: "Synthesize C++ Module",
    exportCloud: "Export Cloud Scripts",
    searchingWeb: "Searching Knowledge Base...",
    autoRigActive: "Auto-Rigging Active",
    motionPreview: "Motion Preview"
  },
  RU: {
    architect: "AI Архитектор",
    build: "Сборка",
    deploy: "Деплой",
    project: "Проект",
    settings: "Настройки",
    aiPrompt: "Спросить Архитектора...",
    statusReady: "Готов",
    statusCompiling: "Компиляция...",
    profile: "Профиль",
    terminal: "Терминал",
    explorer: "Проводник",
    tabScene: "Сцена",
    tabCode: "Код",
    tabNetGraph: "Сетевой Граф",
    tabAssets: "Студия Ассетов",
    tabOrchestrator: "Оркестратор",
    generate: "Генерировать",
    deployCluster: "Запуск Кластера",
    stopCluster: "Остановить Кластер",
    apply: "Применить",
    scanArchitecture: "Аудит Архитектуры",
    compileBuild: "Скомпилировать",
    projectHierarchy: "Иерархия Проекта",
    kernelOutput: "Вывод Ядра",
    complexity: "Сложность",
    threads: "Потоки",
    diagnostics: "Диагностика",
    autoPatch: "Авто-Патч",
    meshGen: "Генерация Мешей",
    motionBank: "Банк Движений",
    loadConcept: "Загрузить Концепт",
    directives: "Директивы",
    startSynthesis: "Запустить Синтез",
    synthesizing: "Синтезирую...",
    finalizeImport: "Завершить Импорт",
    neuralMotion: "Нейро-Синтез Анимаций",
    describeMotion: "Опишите движение (напр. 'Прыжок')...",
    synthesizeAnimation: "Синтезировать Анимацию",
    topology: "Анализ Топологии",
    addNode: "Добавить узел...",
    synthesizeNode: "Синтез",
    pipeline: "Конвейер",
    lodIndex: "Индекс LOD",
    nodeLoad: "Нагрузка Узла",
    infrastructure: "Мониторинг Инфраструктуры",
    realtimeStream: "Прямой поток: Активен",
    specYaml: "Спецификация YAML",
    provisioning: "Развертывание...",
    autosave: "Автосохранение",
    enabled: "Активно",
    thinking: "Архитектор размышляет...",
    proactiveContext: "Проактивный Контекст",
    recArch: "Рекомендация по Архитектуре",
    sysNominal: "Системы в норме. Провожу фоновый аудит производительности...",
    assetPreview: "Предпросмотр Ассета",
    weightsConverged: "Веса Согласованы",
    neuralStandby: "Нейросеть в режиме ожидания",
    addRetargeter: "Добавить в Ретаргетер",
    synthesizeModule: "Синтезировать C++ Модуль",
    exportCloud: "Экспорт Cloud-скриптов",
    searchingWeb: "Поиск в базе знаний...",
    autoRigActive: "Auto-Rigging активен",
    motionPreview: "Превью движения"
  }
};
